resources:
  - name: connect
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: connect2
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: resource_pipelines123
    type: GitRepo
    configuration:
      gitProvider: git_v
      path: vishnurao12/pipelines
      files: 
        include: ^README.md$
      branches:
        include: ^master$
pipelines:
  - name: testing_123
    steps:
      - name: first
        type: Bash
        configuration:
          inputResources: 
           - name: resource_pipelines123
             trigger: false
           - name: connect
             trigger: false
          integrations:
           - name: git_v
        execution:
          onExecute:
            - printenv
            - pushd $res_resource_pipelines123_resourcePath
            - ls
          onSuccess:
            - pushd $res_resource_pipelines123_resourcePath
            - ls
      - name: second
        type: Bash
        configuration:
          inputResources: 
           - name: resource_pipelines123
             trigger: false
           - name: connect
             trigger: false
          integrations:
           - name: git_v
        execution:
          onExecute:
            - printenv
            - pushd $res_resource_pipelines123_resourcePath
            - ls
          onSuccess:
            - pushd $res_resource_pipelines123_resourcePath
            - ls
      - name: myStepa1
        type: Bash
        configuration:
          inputResources: 
           - name: resource_pipelines123
             trigger: false
          integrations:
           - name: git_v
          inputSteps: 
           - name: first
           - name: second
          affinityGroup: "group1" 
        execution:
          onExecute:
            - printenv
            - pushd $res_resource_pipelines123_resourcePath
            - ls
          onSuccess:
            - pushd $res_resource_pipelines123_resourcePath
            - ls
      - name: myStepa2
        type: Bash
        configuration:
          inputResources: 
           - name: resource_pipelines123
             trigger: false
          integrations:
           - name: git_v
          inputSteps: 
           - name: myStepa1
          affinityGroup: "group1"
          priority: 20 # optional
        execution:
          onExecute:
            - printenv
            - pushd $res_resource_pipelines123_resourcePath
            - ls
          onSuccess:
            - pushd $res_resource_pipelines123_resourcePath
            - ls
      - name: myStepa3
        type: Bash
        configuration:
          inputResources: 
           - name: resource_pipelines123
             trigger: false
          integrations:
           - name: git_v
          inputSteps: 
           - name: myStepa1
          affinityGroup: "group1"
          priority: 30
        execution:
          onExecute:
            - printenv
            - pushd $res_resource_pipelines123_resourcePath
            - ls
          onSuccess:
            - pushd $res_resource_pipelines123_resourcePath
            - ls
      - name: myStepa4
        type: Bash
        configuration:
          inputResources: 
            - name: resource_pipelines123
              trigger: false
          integrations:
            - name: git_v
          inputSteps: 
            - name: myStepa3
          affinityGroup: "group2"
          outputResources:
            - name: connect2
        execution:
          onExecute:
            - printenv
          onSuccess:
            - write_output connect2 "testKey=$run_id"
      - name: myStepa5
        type: Bash
        configuration:
          inputResources: 
            - name: connect2
              trigger: true
          integrations:
            - name: git_v
          affinityGroup: "group2"
        execution:
          onExecute:
            - printenv
            - ls
          onSuccess:
            - ls
