resources:
  - name: connecting_resource
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
      
  - name: ns_dockerbuild_gitRepo
    type: GitRepo
    configuration:
      path: vishnurao12/sample-script
      gitProvider: git_v
      branches: 
        include: master


pipelines:
  - name: docker_push


      - name: To_build_Docker_Image
        type: DockerBuild
        configuration:

          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: 10.70.35.43:8082/docker-local/node

          dockerImageTag: latest
          integrations:
            - name: art_v

          inputResources:
            - name: ns_dockerbuild_gitRepo 
            - name: connecting_resource


      - name: To_Push_Docker_Image
        type: DockerPush
        configuration:

          autoPublishBuildInfo: false #IMPORTANGT******************* : if this is true then only we need outputResource in DockerPush and no need of publishBuildInfo step
          targetRepository: docker-local #required
          integrations:
            - name: art_v 
          inputSteps:
            - name: To_build_Docker_Image
