resources:
  - name: auto_gitRepo123
    type: GitRepo
    configuration:
      path: ~vishnur/sample_tests
      gitProvider: vishnur_bbs
      branches:
        include: ^master$
pipelines:
  - name: testing_flow_1
    steps:
      - name: step_1_test
        type: Bash
        configuration:
          integrations:
            - name: gcpenvInt
          inputResources:
            - name: auto_gitRepo123
              trigger: False
        execution:
          onStart:
            - echo "hello"
            - pushd $res_auto_gitRepo123_resourcePath
            - export pipeenv='gcp'
            - cd tests
            - chmod +x test.sh 
            - ./test.sh gcpenvInt

#       - name: step_2_test
#         type: Bash
#         configuration:
#           inputSteps: 
#             - name: step_1_test
#         execution:
#           onStart:
#             - printenv


#   - name: testing_flow_2
#     steps:
#       - name: step_2_test
#         type: Bash
#         execution:
#           onStart:
#              - echo "hello"
#   - name: testing_flow_3
#     steps:
#       - name: step_3_test
#         type: Bash
#         execution:
#           onStart:
#              - echo "hello"
#   - name: testing_flow_4
#     steps:
#       - name: step_4_test
#         type: Bash
#         execution:
#           onStart:
#              - echo "hello"
