pipelines:
  - name: test_pipe
    steps:
      - name: Upload_to_artifactory
        type: Bash
        configuration:
          integrations:
            - name: art_v 
        execution:
          onExecute:
            - echo automation > test1.sh
            - jfrog rt u test.sh testupload-generic-local/test1.sh
            - ls
            - add_pipeline_files test.sh mytestfile #test.sh is the file and mytestfile is the filename.
            - mkdir /testfolder # create test folder at the root
      - name: Download_to_artifactory
        type: Bash
        configuration:
          integrations:
            - name: art_v 
          inputSteps:
            - name: Upload_to_artifactory
        execution:
          onExecute:
            - echo automation > test.sh
            - jfrog rt dl testupload-generic-local/test1.sh
            - ls


    #adding an artifact to pipeline state using pipelines utility function 


            - restore_pipeline_files mytestfile /testfolder/test.sh # restoring the Artifactory from the pipeline state.
            - cat /testfolder/test.sh
