pipelines:
  - name: test_pipe
    steps:
      - name: Upload_to_artifactory
        type: Bash
        configuration:
          integrations:
            - name: art_v
        execution:
          onExecute:
            - echo automation > test.sh
            - jfrog rt u test.sh example-repo-local/setup/test.sh --insecure-tls
