pipelines:
  - name: test_pipe
    steps:
      - name: Upload_to_artifactory
        type: Bash
        configuration:
          integrations:
            - name: bsArt 
        execution:
          onExecute:
            - echo automation > test1.sh
            - jfrog rt u test1.sh example-repo-local/test1.sh
            - ls
            - add_pipeline_files test1.sh mytestfile #test.sh is the file and mytestfile is the filename.

      - name: Download_frm_artifactory
        type: Bash
        configuration:
          integrations:
            - name: bsArt 
          inputSteps:
            - name: Upload_to_artifactory
        execution:
          onExecute:

            - mkdir /testfolder # create test folder at the root
            - jfrog rt dl example-repo-local/test1.sh
            - ls


    #adding an artifact to pipeline state using pipelines utility function 


            - restore_pipeline_files mytestfile /testfolder/test.sh # restoring the Artifactory from the pipeline state.
            - cat /testfolder/test.sh
