resources:
  - name: azure_load_git
    type: GitRepo
    configuration:
      path: vishnurao12/azure
      gitProvider: git_v
      branches:
        include: ^master$

  - name: load_azure
    type: CronTrigger
    configuration:
      interval: "*/5 * * * *"

pipelines:
  - name: Azure_load_test
    steps:
      - name: Post_int_pipeline
        type: Bash
        configuration:
          integrations:
            - name: azure_test
          inputResources:
            - name: azure_load_git
              trigger: False
        execution:
          onStart:
            - pushd $res_azure_load_git_resourcePath
            - export dataPoolModule=false
            - export baseUrl="${int_azure_test_baseUrl}"
            - export accessToken="${int_azure_test_accessToken}"
            - ./test.sh

      - name: load_pipelines_test
        type: Bash
        configuration:
          integrations:
            - name: azure_test
          inputResources:
            - name: load_azure
            - name: azure_load_git
        execution:
          onStart:
            - echo "This will run on one machine every 5 mins"
            - pushd $res_azure_load_git_resourcePath
            - restore_pipeline_files my_file.xlsx load_test.xlsx
            - export dataPoolModule=true
            - export RunNumber="${run_number}"
            - export baseUrl="${int_azure_test_baseUrl}"
            - export accessToken="${int_azure_test_accessToken}"
            - ./test.sh
            - add_pipeline_files load_test.xlsx my_file.xlsx
            - ls 
