resources:
  - name: connecting_resource_lang
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2

pipelines:
  - name: lang_test
    steps:
      - name: u18java8
        type: Bash
        configuration:
          nodePool: u18
          runtime: 
            type: image
            image: 
              auto:
                language: java
                versions:
                  - "8"
          inputResources:
            - name: connecting_resource_lang
        execution:
          onExecute:
            - printenv
      - name: u18java11
        type: Bash
        configuration:
          nodePool: u18
          runtime: 
            type: image
            image: 
              auto:
                language: java
                versions:
                  - "11"
          inputSteps: 
            - name: u18java8
        execution:
          onExecute:
            - printenv
      - name: u18java13
        type: Bash
        configuration:
          nodePool: u18
          runtime: 
            type: image
            image: 
              auto:
                language: java
                versions:
                  - "8"
          inputSteps: 
            - name: u18java11
        execution:
          onExecute:
            - printenv
      - name: u18go1137
        type: Bash
        configuration:
          nodePool: u18
          runtime: 
            type: image
            image: 
              auto:
                language: go
                versions:
                  - "1.13.7"
          inputSteps: 
            - name: u18java13
        execution:
          onExecute:
            - printenv
      - name: u18go11214
        type: Bash
        configuration:
          nodePool: u18
          runtime: 
            type: image
            image: 
              auto:
                language: go
                versions:
                  - "1.12.14"
          inputSteps: 
            - name: u18go1137
        execution:
          onExecute:
            - printenv
      - name: u18go11113
        type: Bash
        configuration:
          nodePool: u18
          runtime: 
            type: image
            image: 
              auto:
                language: go
                versions:
                  - "1.11.13"
          inputSteps: 
            - name: u18go11214
        execution:
          onExecute:
            - printenv
      - name: u18node10180
        type: Bash
        configuration:
          nodePool: u18
          runtime: 
            type: image
            image: 
              auto:
                language: node
                versions:
                  - "10.18.0"
          inputSteps: 
            - name: u18go11113
        execution:
          onExecute:
            - printenv
      - name: u18node12140
        type: Bash
        configuration:
          nodePool: u18
          runtime: 
            type: image
            image: 
              auto:
                language: node
                versions:
                  - "12.14.0"
          inputSteps: 
            - name: u18node10180
        execution:
          onExecute:
            - printenv
      - name: u18cpp800
        type: Bash
        configuration:
          nodePool: u18
          runtime: 
            type: image
            image: 
              auto:
                language: cpp
                versions:
                  - "8.0.0"
          inputSteps: 
            - name: u18node12140
        execution:
          onExecute:
            - printenv
      - name: u18cpp900
        type: Bash
        configuration:
          nodePool: u18
          runtime: 
            type: image
            image: 
              auto:
                language: cpp
                versions:
                  - "9.0.0"
          inputSteps: 
            - name: u18cpp800
        execution:
          onExecute:
            - printenv

      - name: u16java8
        type: Bash
        configuration:
          nodePool: u16
          runtime: 
            type: image
            image: 
              auto:
                language: java
                versions:
                  - "8"
          inputResources:
            - name: connecting_resource_lang
        execution:
          onExecute:
            - printenv
      - name: u16java11
        type: Bash
        configuration:
          nodePool: u16
          runtime: 
            type: image
            image: 
              auto:
                language: java
                versions:
                  - "11"
          inputSteps: 
            - name: u16java8
        execution:
          onExecute:
            - printenv
      - name: u16java13
        type: Bash
        configuration:
          nodePool: u16
          runtime: 
            type: image
            image: 
              auto:
                language: java
                versions:
                  - "8"
          inputSteps: 
            - name: u16java11
        execution:
          onExecute:
            - printenv
      - name: u16go1137
        type: Bash
        configuration:
          nodePool: u16
          runtime: 
            type: image
            image: 
              auto:
                language: go
                versions:
                  - "1.13.7"
          inputSteps: 
            - name: u16java13
        execution:
          onExecute:
            - printenv
      - name: u16go11214
        type: Bash
        configuration:
          nodePool: u16
          runtime: 
            type: image
            image: 
              auto:
                language: go
                versions:
                  - "1.12.14"
          inputSteps: 
            - name: u16go1137
        execution:
          onExecute:
            - printenv
      - name: u16go11113
        type: Bash
        configuration:
          nodePool: u16
          runtime: 
            type: image
            image: 
              auto:
                language: go
                versions:
                  - "1.11.13"
          inputSteps: 
            - name: u16go11214
        execution:
          onExecute:
            - printenv
      - name: u16node10180
        type: Bash
        configuration:
          nodePool: u16
          runtime: 
            type: image
            image: 
              auto:
                language: node
                versions:
                  - "10.18.0"
          inputSteps: 
            - name: u16go11113
        execution:
          onExecute:
            - printenv
      - name: u16node12140
        type: Bash
        configuration:
          nodePool: u16
          runtime: 
            type: image
            image: 
              auto:
                language: node
                versions:
                  - "12.14.0"
          inputSteps: 
            - name: u16node10180
        execution:
          onExecute:
            - printenv
      - name: u16cpp800
        type: Bash
        configuration:
          nodePool: u16
          runtime: 
            type: image
            image: 
              auto:
                language: cpp
                versions:
                  - "8.0.0"
          inputSteps: 
            - name: u16node12140
        execution:
          onExecute:
            - printenv
      - name: u16cpp900
        type: Bash
        configuration:
          nodePool: u16
          runtime: 
            type: image
            image: 
              auto:
                language: cpp
                versions:
                  - "9.0.0"
          inputSteps: 
            - name: u16cpp800
        execution:
          onExecute:
            - printenv

      - name: win_2019java8
        type: PowerShell
        configuration:
          nodePool: win_2019
          runtime: 
            type: image
            image: 
              auto:
                language: java
                versions:
                  - "8"
          inputResources:
            - name: connecting_resource_lang
        execution:
          onExecute:
            - write-output "Hi"
      - name: win_2019java11
        type: PowerShell
        configuration:
          nodePool: win_2019
          runtime: 
            type: image
            image: 
              auto:
                language: java
                versions:
                  - "11"
          inputSteps: 
            - name: win_2019java8
        execution:
          onExecute:
            - write-output "Hi"
      - name: win_2019go113
        type: PowerShell
        configuration:
          nodePool: win_2019
          runtime: 
            type: image
            image: 
              auto:
                language: go
                versions:
                  - "11.3"
          inputSteps: 
            - name: win_2019java11
        execution:
          onExecute:
            - write-output "Hi"
      - name: win_2019go112
        type: PowerShell
        configuration:
          nodePool: win_2019
          runtime: 
            type: image
            image: 
              auto:
                language: go
                versions:
                  - "1.12"
          inputSteps: 
            - name: win_2019go113
        execution:
          onExecute:
            - write-output "Hi"
      - name: win_2019go111
        type: PowerShell
        configuration:
          nodePool: win_2019
          runtime: 
            type: image
            image: 
              auto:
                language: go
                versions:
                  - "11.1"
          inputSteps: 
            - name: win_2019go112
        execution:
          onExecute:
            - write-output "Hi"
      - name: win_20191018
        type: PowerShell
        configuration:
          nodePool: win_2019
          runtime: 
            type: image
            image: 
              auto:
                language: node
                versions:
                  - "10.18"
          inputSteps: 
            - name: win_2019go111
        execution:
          onExecute:
            - write-output "Hi"
      - name: win_20191214
        type: PowerShell
        configuration:
          nodePool: win_2019
          runtime: 
            type: image
            image: 
              auto:
                language: node
                versions:
                  - "12.14"
          inputSteps: 
            - name: win_20191018
        execution:
          onExecute:
            - write-output "Hi"
      - name: win_2019817
        type: PowerShell
        configuration:
          nodePool: win_2019
          runtime: 
            type: image
            image: 
              auto:
                language: node
                versions:
                  - "8.17"
          inputSteps: 
            - name: win_20191214
        execution:
          onExecute:
            - write-output "Hi"
      - name: win_2019cpp800
        type: PowerShell
        configuration:
          nodePool: win_2019
          runtime: 
            type: image
            image: 
              auto:
                language: cpp
                versions:
                  - "8.0.0"
          inputSteps: 
            - name: win_20191214
        execution:
          onExecute:
            - write-output "Hi"
      - name: win_2019cpp900
        type: PowerShell
        configuration:
          nodePool: win_2019
          runtime: 
            type: image
            image: 
              auto:
                language: cpp
                versions:
                  - "9.0.0"
          inputSteps: 
            - name: win_2019cpp800
        execution:
          onExecute:
            - write-output "Hi"
      - name: win_2019dotnet21
        type: PowerShell
        configuration:
          nodePool: win_2019
          runtime: 
            type: image
            image: 
              auto:
                language: dotnet
                versions:
                  - "2.1"
          inputSteps: 
            - name: win_2019cpp900
        execution:
          onExecute:
            - write-output "Hi"
      - name: win_2019dotnet31
        type: PowerShell
        configuration:
          nodePool: win_2019
          runtime: 
            type: image
            image: 
              auto:
                language: dotnet
                versions:
                  - "3.1"
          inputSteps: 
            - name: win_2019dotnet21
        execution:
          onExecute:
            - write-output "Hi"

      - name: c7nodejava8
        type: Bash
        configuration:
          nodePool: c7node
          runtime: 
            type: image
            image: 
              auto:
                language: java
                versions:
                  - "8"
          inputResources:
            - name: connecting_resource_lang
        execution:
          onExecute:
            - printenv
      - name: c7nodejava11
        type: Bash
        configuration:
          nodePool: c7node
          runtime: 
            type: image
            image: 
              auto:
                language: java
                versions:
                  - "11"
          inputSteps: 
            - name: c7nodejava8
        execution:
          onExecute:
            - printenv
      - name: c7nodego1137
        type: Bash
        configuration:
          nodePool: c7node
          runtime: 
            type: image
            image: 
              auto:
                language: go
                versions:
                  - "1.13.7"
          inputSteps: 
            - name: c7nodejava11
        execution:
          onExecute:
            - printenv
      - name: c7nodego11214
        type: Bash
        configuration:
          nodePool: c7node
          runtime: 
            type: image
            image: 
              auto:
                language: go
                versions:
                  - "1.12.14"
          inputSteps: 
            - name: c7nodego1137
        execution:
          onExecute:
            - printenv
      - name: c7nodego11113
        type: Bash
        configuration:
          nodePool: c7node
          runtime: 
            type: image
            image: 
              auto:
                language: go
                versions:
                  - "1.11.13"
          inputSteps: 
            - name: c7nodego11214
        execution:
          onExecute:
            - printenv
      - name: c7node10180
        type: Bash
        configuration:
          nodePool: c7node
          runtime: 
            type: image
            image: 
              auto:
                language: node
                versions:
                  - "10.18.0"
          inputSteps: 
            - name: c7nodego11113
        execution:
          onExecute:
            - printenv
      - name: c7node12140
        type: Bash
        configuration:
          nodePool: c7node
          runtime: 
            type: image
            image: 
              auto:
                language: node
                versions:
                  - "12.14.0"
          inputSteps: 
            - name: c7node10180
        execution:
          onExecute:
            - printenv
      - name: c7nodecpp342
        type: Bash
        configuration:
          nodePool: c7node
          runtime: 
            type: image
            image: 
              auto:
                language: cpp
                versions:
                  - "3.4.2"
          inputSteps: 
            - name: c7node12140
        execution:
          onExecute:
            - printenv

      - name: rheljava8
        type: Bash
        configuration:
          nodePool: rhel
          runtime: 
            type: image
            image: 
              auto:
                language: java
                versions:
                  - "8"
          inputResources:
            - name: connecting_resource_lang
        execution:
          onExecute:
            - printenv
      - name: rheljava11
        type: Bash
        configuration:
          nodePool: rhel
          runtime: 
            type: image
            image: 
              auto:
                language: java
                versions:
                  - "11"
          inputSteps: 
            - name: rheljava8
        execution:
          onExecute:
            - printenv
      - name: rhelgo1137
        type: Bash
        configuration:
          nodePool: rhel
          runtime: 
            type: image
            image: 
              auto:
                language: go
                versions:
                  - "1.13.7"
          inputSteps: 
            - name: rheljava11
        execution:
          onExecute:
            - printenv
      - name: rhelgo11214
        type: Bash
        configuration:
          nodePool: rhel
          runtime: 
            type: image
            image: 
              auto:
                language: go
                versions:
                  - "1.12.14"
          inputSteps: 
            - name: rhelgo1137
        execution:
          onExecute:
            - printenv
      - name: rhelgo11113
        type: Bash
        configuration:
          nodePool: rhel
          runtime: 
            type: image
            image: 
              auto:
                language: go
                versions:
                  - "1.11.13"
          inputSteps: 
            - name: rhelgo11214
        execution:
          onExecute:
            - printenv
      - name: rhel10180
        type: Bash
        configuration:
          nodePool: rhel
          runtime: 
            type: image
            image: 
              auto:
                language: node
                versions:
                  - "10.18.0"
          inputSteps: 
            - name: rhelgo11113
        execution:
          onExecute:
            - printenv
      - name: rhel12140
        type: Bash
        configuration:
          nodePool: rhel
          runtime: 
            type: image
            image: 
              auto:
                language: node
                versions:
                  - "12.14.0"
          inputSteps: 
            - name: rhel10180
        execution:
          onExecute:
            - printenv
      - name: rhelcpp342
        type: Bash
        configuration:
          nodePool: rhel
          runtime: 
            type: image
            image: 
              auto:
                language: cpp
                versions:
                  - "3.4.2"
          inputSteps: 
            - name: rhel12140
        execution:
          onExecute:
            - printenv
