pipelines:
  - name: pipelines_auto1
    steps:
      - name: myStep1
        type: Bash
        configuration: 
          runtime:
            type: host
        execution:
          onExecute:
            - docker images
            - docker images | grep docker.bintray.io/jfrog/pipelines-u18go | grep 1.13.7
            - docker images | grep docker.bintray.io/jfrog/pipelines-u18go | grep 1.12.14
            - docker images | grep docker.bintray.io/jfrog/pipelines-u18go | grep 1.11.13 
            - a=(vishnu rao)
            - c=(1 2)
            - for i in "${a[@]}"; do for j in "${c[@]}"; do echo $i $j; done; done  

