resources:
 - name: resource_pipelines12
   type: GitRepo
   configuration:
     gitProvider: git_v
     path: vishnurao12/pipelines
     files: 
       include: ^README.md$

pipelines:
  - name: testing_123
    steps:
      - name: myStep112
        type: Bash
        configuration:
         inputResources: 
           - name: resource_pipelines12
         integrations:
           - name: git_v
        execution:
          onExecute:
            - printenv
            - pushd $res_resource_pipelines12_resourcePath
            - ls
            - echo "hi"
          onSuccess:
            - pushd $res_resource_pipelines12_resourcePath
            - ls



      
