
pipelines:
  - name: sleep_test_win
    steps:
      - name: win_2019
        type: PowerShell
        configuration:
          nodePool: win_2019
        execution:
          onExecute:
            - write-output  "executing step..."
            - Start-Sleep -s 300
