resources:
  - name: connecting_resource_node_test12
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2

pipelines:
  - name: node_test
    steps:
      - name: myStep112
        type: Bash
        configuration:
          outputResources: 
            - name: connecting_resource_node_test12
#               trigger: false
          integrations:
            - name: git_v
        execution:
          onExecute:
            - write_output connecting_resource_node_test12 "test:value"

      - name: static
        type: Bash
        configuration:
          nodePool: static
          inputResources:
            - name: connecting_resource_node_test12
        execution:
          onExecute:
            - printenv
            - docker images
            - sleep 10m

      - name: gcp_dynamic
        type: Bash
        configuration:
          nodePool: u16dynamic
          inputResources:
            - name: connecting_resource_node_test12
        execution:
          onExecute:
            - printenv
            - docker images
            - sleep 10m

      - name: k8sdynamic
        type: Bash
        configuration:
          nodePool: k8sdynamic
          inputResources:
            - name: connecting_resource_node_test12
        execution:
          onExecute:
            - printenv
            - docker images
            - sleep 10m



      
