#PIPE_2138.yml
resources:
  - name: auto_GitRepotest
    type: GitRepo
    configuration:
      gitProvider: git_v
      path: vishnurao12/pipelines
      files:  
        include: random/test.sh

pipelines:
  - name: pipeline_git
    steps:   
      - name: stepA
        type: Bash
        configuration:
          chronological: true
          inputResources:
            - name: auto_GitRepotest
              trigger: true 
        execution:
          onExecute:
            - printenv
 
      - name: stepB
        type: Bash
        configuration:
          chronological: true
          inputSteps: # optional
            - name: stepA
          inputResources:
            - name: auto_GitRepotest
              trigger: true 
        execution:
          onExecute:
            - printenv
