
pipelines:
  - name: sample
    steps:
      - name: testBash
        type: Bash
      #  configuration:
        #  nodePool: gcp_test1
        execution:
          onExecute:
            - echo "hello!"
