resources:
 - name: testp123
   type: GitRepo
   configuration:
     gitProvider: git_v
     path: vishnurao12/pipelines

pipelines:
  - name: testP123
    steps:
      - name: testP123
        type: PowerShell
        configuration:
          nodePool: win_2019_1
        execution:
          onExecute:
            - dotnet --version
            - if($(dotnet --version) -ne "3.1.102"){
              Write-Error "Stop" -ErrorAction Stop
              }
