
pipelines:
  - name: sample3
    steps:
      - name: testBash3
        type: Bash
#         configuration:
#           nodePool: rhel7
#           runtime: # optional            
#             type: image
#             image: # should be present if type is image
#               auto:
#                 language: java
#                 versions:
#                   - "8"
        
        execution:
          onExecute:
            - echo "hello!"
