resources:
 - name: resource_pipelines12
   type: PropertyBag
   configuration:
     test: values12

pipelines:
  - name: testing_123
    steps:
#       - name: myStep112
#         type: Bash
#         configuration:
#           outputResources: 
#             - name: resource_pipelines12
# #               trigger: false
#           integrations:
#             - name: git_v
#         execution:
#           onExecute:
#             - write_output resource_pipelines12 "test:value"

      - name: myStep113
        type: Bash
        configuration:
          inputResources: 
            - name: resource_pipelines12
#               trigger: false
          integrations:
            - name: git_v
        execution:
          onExecute:
            - sleep 1m
            - printenv

      - name: myStep114
        type: Bash
        configuration:
          inputSteps:
            - name: myStep113
          inputResources: 
            - name: resource_pipelines12
#               trigger: false
          integrations:
            - name: git_v
        execution:
          onExecute:
            - printenv
            - df -H /dev/sda1
            - df -H
