resources:
 - name: gitResource
   type: GitRepo
   configuration:
     gitProvider: git_v
     path: vishnurao12/pipelines
pipelines:
  - name: pipelines_test
    steps:
      - name: myStep1
        type: Bash
        configuration: 
         nodePool: gcp-test
         inputResources: # optional
           - name: gitResource
             trigger: true
        execution:
          onExecute:
            - printenv

      - name: myStep2
        type: Bash
        configuration: 
          nodePool: gcp-test
          inputResources: # optional
            - name: gitResource
              trigger: true
 #           inputSteps: 
 #            - name: myStep1
        execution:
          onExecute:
            - printenv




      
