
pipelines:
  - name: sample
    steps:
      - name: testBash
        type: Bash
        configuration:
          nodePool: 16dynamic
        execution:
          onExecute:
            - echo "hello!"
