resources:
 - name: resource_pipelines124512
   type: GitRepo
   configuration:
     gitProvider: git_v
     path: vishnurao12/pipelines
     files: 
       include: ^README.md$
     branches:
       include: ^{{gitBranch}}$
     buildOn:
       pullRequestCreate: true
     cancelPendingRunsOn:
       pullRequestUpdate: true

pipelines:
  - name: testing_12312
    steps:
      - name: myStep112
        type: Bash
        configuration:
         inputResources: 
           - name: resource_pipelines124512
         integrations:
           - name: git_v
        execution:
          onExecute:
            - printenv
            - pushd $res_resource_pipelines124512_resourcePath
            - ls
            - echo "hi"
          onSuccess:
            - pushd $res_resource_pipelines124512_resourcePath
            - ls
