resources:
 - name: resource_pipelines123
   type: GitRepo
   configuration:
     gitProvider: git_v
     path: vishnurao12/pipelines
#      files: 
#        include: ^README.md$
#      branches:
#        include: ^master$
pipelines:
  - name: testing_123
    steps:
      - name: myStep112
        type: Bash
        configuration:
         inputResources: 
           - name: resource_pipelines123
             trigger: false
         integrations:
           - name: git_v
        execution:
          onExecute:
            - printenv
