resources:
  - name: resource_with_immuatable_true 
    type: Gitnp/gittest1
    configuration:      
      test: foo
      bdood: "present"
 
pipelines:
  - name: extensionstest1
    steps:
      - name: step_with_resource_with_immuatable_true
        type: gitcheck/gitstep
        configuration:              
          foo: bar
          inputResources:
            - name: resource_with_immuatable_true
        execution:
          onStart:
            - echo "Preparing for work..."
            - printenv


