pipelines:
  - name: basic1
    steps:
      - name: basic1
        type: Bash
        configuration:
          runtime:
            type: host
        execution:
          onExecute:
            - printenv {{ .Values.foo.bar }}
