      
pipelines:
  - name: lang_test
    steps:
      - name: win_2019go111
        type: PowerShell
        configuration:
          nodePool: win_2019
        execution:
          onExecute:
            - docker images
