      
pipelines:
  - name: lang_test
    steps:
      - name: win_2019dotnet21
        type: PowerShell
        configuration:
          nodePool: win_2019
          runtime: 
            type: image
            image: 
              auto:
                language: dotnetcore
                versions:
                  - "2.1"
        execution:
          onExecute:
            - write-output "Hi"
